# Project information
site_name:             'Zamanian Lab Docs'
site_description:      'An internal resource explaining and documenting lab pipelines'
site_author:           'Zamanian Lab'
site_url:              'https://zamanianlab.org/ZamanianLabDocs'


# Repository
repo_name:             'zamanianlab/ZamanianLabDocs'
repo_url:              'https://github.com/zamanianlab/ZamanianLabDocs'

# Configuration

theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: teal
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - instant
  markdown_extensions:
    - admonition

# Customization
extra:
    social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/zamanianlab
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zamanian_

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

nav:
  - Home:                     index.md
  - Lab Manual:               labmanual.md
  - Lab Protocols:            'protocols/protocols.md'
  - Lab Sheets:               labsheets.md
  - Computational Guide:
    - Overview:               comp_overview.md
    - Local Environment:      comp_local.md
    - GitHub:                 comp_github.md
    - Conda:                  comp_conda.md
    - Homebrew:               comp_homebrew.md
  - Pipelines:
    - Overview:               pipelines_overview.md
    - Data Storage:           pipelines_storage.md
    - Local Pipelines:        pipelines_local.md
    - Server Pipelines:       pipelines_server.md
  - Resources:                resources.md
