# Project information
site_name:             'Zamanian Lab Documentation'
site_description:      'An internal resource explaining and documenting lab pipelines'
site_author:           'Nic Wheeler'
site_url:              'https://zamanianlab.org/ZamanianLabDocs'


# Repository
repo_name:             'zamanianlab/ZamanianLabDocs'
repo_url:              'https://github.com/zamanianlab/ZamanianLabDocs'

# Configuration
theme:
  name: 'material'
  favicon: 'assets/images/dna.ico'
  pallete:
    primary: 'black'
    accent: 'red'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/zamanianlab'
    - type: 'twitter'
      link: 'https://twitter.com/zamanian_'

nav:
  - Home:                     index.md
  - Lab Manual:               labmanual.md
  - Computational Onboarding: onboarding.md
  - Lab Pipelines:            pipelines.md
  - Adding Documentation:     updating.md
