site_name: Zamanian Lab Documentation
theme: readthedocs
repo_url: https://github.com/zamanianlab/ZamanianLabDocs


markdown_extensions:
    - admonition
    - toc:
        permalink: True
        separator: "_"
    - fenced_code

nav:
  - Home: index.md
  - Conda: conda.md
