site_name:             Zamanian Lab Documentation
theme:                 'material'
repo_url:              https://github.com/zamanianlab/ZamanianLabDocs


markdown_extensions:
    - admonition
    - codehilite

nav:
  - Home:                 index.md
  - Adding Documentation: updating.md
